[[redirects]]
  from = "/api/*"
  to = "https://artmanager-demo.netlify.app/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "POST"}